version: "3.7"

services:
    gateway:
        build:
            context: gateway
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        env_file:
             - ./gateway/.env
        depends_on:
            - elasticsearch
            - kibana
    writer:
        build:
            context: writer
            dockerfile: Dockerfile
        env_file:
             - ./writer/.env
        depends_on:
            elasticsearch:
                condition: service_healthy

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - elasticsearch-volume:/usr/share/elasticsearch/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl --silent --fail http://localhost:9200/_cluster/health || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 5

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.4.0
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601

volumes:
    elasticsearch-volume:
        driver: local
